spring:
  application:
    name: service-to-test-prometheus-monitoring



management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8086